// moon: The build system and package manager for MoonBit.
// Copyright (C) 2024 International Digital Economy Academy
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// For inquiries, you can contact us via e-mail at jichuruanjian@idea.edu.cn.

use n2::densemap::Index;
use n2::graph::{BuildId, FileId, Graph};
use std::{
    collections::{HashMap, HashSet},
    io::Write,
    path::{Path, PathBuf},
    sync::LazyLock,
};

pub use moonutil::dry_run::PathNormalizer;

const ENV_VAR: &str = "MOON_TEST_DUMP_BUILD_GRAPH";
static DRY_RUN_TEST_OUTPUT: LazyLock<Option<String>> =
    LazyLock::new(|| std::env::var(ENV_VAR).ok());

/// Print build commands from a State
pub fn print_build_commands(
    graph: &Graph,
    default: &[FileId],
    source_dir: &Path,
    target_dir: &Path,
) {
    let replacer = PathNormalizer::new_with_target_dir(source_dir, target_dir);

    if !default.is_empty() {
        let mut sorted_default = default.to_vec();
        sorted_default.sort_by_key(|a| a.index());
        let builds: Vec<BuildId> = stable_toposort_graph(graph, &sorted_default);
        for b in builds.iter() {
            let build = &graph.builds[*b];
            if let Some(cmdline) = &build.cmdline {
                let res = replacer.normalize_command(cmdline);
                println!("{}", res);
            }
        }
    }

    try_debug_dump_build_graph_to_file(graph, default, source_dir, target_dir);
}

pub struct DryRunCommand<'a> {
    pub command: Option<&'a str>,
    pub command_kind: DryRunCommandKind,
    pub inputs: &'a [PathBuf],
    pub outputs: &'a [PathBuf],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DryRunCommandKind {
    /// Command produced from an argv vector and rendered for the executor.
    Argv,
    /// Command intentionally composed with shell syntax from trusted argv fragments.
    Shell,
}

impl<'a> DryRunCommand<'a> {
    pub fn normalized_command(&self, replacer: &PathNormalizer) -> Option<String> {
        self.command.map(|command| match self.command_kind {
            DryRunCommandKind::Argv => replacer.normalize_command(command),
            DryRunCommandKind::Shell => normalize_shell_command(replacer, command),
        })
    }
}

// This is for shell commandlines generated by lowering from trusted argv
// fragments, not a general-purpose shell rewriter.
fn normalize_shell_command(replacer: &PathNormalizer, command: &str) -> String {
    moonutil::shlex::split_unix(command)
        .into_iter()
        .map(|arg| {
            if is_shell_control_operator(&arg) {
                arg
            } else {
                let normalized = replacer.normalize_command_arg(&arg);
                moonutil::shlex::join_unix(std::iter::once(normalized.as_str()))
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn is_shell_control_operator(s: &str) -> bool {
    matches!(
        s,
        "&&" | "||" | "|" | ";" | "<" | ">" | ">>" | "2>" | "2>&1"
    )
}

pub fn try_debug_dump_commands_to_file<'a>(
    commands: impl IntoIterator<Item = DryRunCommand<'a>>,
    source_dir: &Path,
    target_dir: &Path,
) {
    let Some(out_file) = DRY_RUN_TEST_OUTPUT.as_deref() else {
        return;
    };

    let replacer = PathNormalizer::new_with_target_dir(source_dir, target_dir);
    let mut nodes = commands
        .into_iter()
        .map(|command| {
            let mut inputs = command
                .inputs
                .iter()
                .map(|path| replacer.normalize_path(&path.to_string_lossy()))
                .collect::<Vec<_>>();
            inputs.sort();
            let outputs = command
                .outputs
                .iter()
                .map(|path| replacer.normalize_path(&path.to_string_lossy()))
                .collect::<Vec<_>>();
            BuildNode {
                command: command.normalized_command(&replacer),
                inputs,
                outputs,
            }
        })
        .collect::<Vec<_>>();

    nodes.sort_by(|a, b| a.outputs.cmp(&b.outputs));
    let file = std::fs::File::create(out_file).expect("Failed to create dry-run dump target");
    BuildGraphDump { nodes }
        .dump_to(file)
        .expect("Failed to dump to target output");
}

#[derive(Debug)]
struct BuildGraphDump {
    nodes: Vec<BuildNode>,
}

impl BuildGraphDump {
    fn dump_to(&self, out: impl Write) -> anyhow::Result<()> {
        let mut writer = std::io::BufWriter::new(out);
        for node in &self.nodes {
            serde_json::to_writer(&mut writer, node)?;
            writeln!(&mut writer)?;
        }
        Ok(())
    }
}

#[derive(Debug, serde::Serialize)]
struct BuildNode {
    command: Option<String>,
    inputs: Vec<String>,
    outputs: Vec<String>,
}

fn debug_dump_build_graph(
    graph: &n2::graph::Graph,
    input_files: &[FileId],
    source_dir: &Path,
    target_dir: &Path,
) -> BuildGraphDump {
    let replacer = PathNormalizer::new_with_target_dir(source_dir, target_dir);

    let accessible_nodes = dfs_for_accessible_nodes(graph, input_files);
    generate_from_nodes(graph, accessible_nodes, &replacer)
}

// FIXME: `MOON_TEST_DUMP_BUILD_GRAPH` is integration-test infrastructure kept
// in production-facing dry-run code only so existing snapshot tests can keep
// invoking the compiled `moon` binary. Gate or relocate this once the test
// harness no longer needs the runtime hook.
fn try_debug_dump_build_graph_to_file(
    build_graph: &n2::graph::Graph,
    default_files: &[n2::graph::FileId],
    source_dir: &Path,
    target_dir: &Path,
) {
    let Some(out_file) = DRY_RUN_TEST_OUTPUT.as_deref() else {
        return;
    };

    let file = std::fs::File::create(out_file).expect("Failed to create dry-run dump target");
    let dump = debug_dump_build_graph(build_graph, default_files, source_dir, target_dir);
    dump.dump_to(file).expect("Failed to dump to target output");
}

fn dfs_for_accessible_nodes(graph: &n2::graph::Graph, start_files: &[FileId]) -> Vec<BuildId> {
    let mut stack = Vec::<FileId>::new();
    stack.extend_from_slice(start_files);
    let mut visited_builds = HashSet::new();
    let mut accessible_builds = vec![];

    while let Some(fid) = stack.pop() {
        let file = graph
            .files
            .by_id
            .lookup(fid)
            .expect("Unknown file in graph");
        if let Some(bid) = file.input
            && visited_builds.insert(bid)
        {
            let build = graph.builds.lookup(bid).expect("Unknown build in graph");
            accessible_builds.push(bid);
            // FIXME: This preserves the current graph dump behavior, but raw
            // `ins.ids` collapses explicit, implicit, order-only, and
            // validation/lazy inputs. Follow up by using the n2 accessor that
            // matches the intended dry-run graph snapshot semantics.
            for &in_fid in &build.ins.ids {
                stack.push(in_fid);
            }
        }
    }

    accessible_builds
}

fn generate_from_nodes(
    graph: &n2::graph::Graph,
    accessible_nodes: impl IntoIterator<Item = BuildId>,
    replacer: &PathNormalizer,
) -> BuildGraphDump {
    let mut nodes = vec![];
    for node in accessible_nodes {
        let node = graph.builds.lookup(node).expect("Unknown build in graph");
        let command = node
            .cmdline
            .as_ref()
            .map(|cmd| replacer.normalize_command(cmd));
        let mut inputs = node
            .ins
            .ids
            .iter()
            .map(|&id| {
                let file = graph.files.by_id.lookup(id).expect("Unknown node in graph");
                replacer.normalize_path(&file.name)
            })
            .collect::<Vec<_>>();
        inputs.sort();
        let outputs = node
            .outs
            .ids
            .iter()
            .map(|&id| {
                let file = graph.files.by_id.lookup(id).expect("Unknown node in graph");
                replacer.normalize_path(&file.name)
            })
            .collect::<Vec<_>>();
        nodes.push(BuildNode {
            command,
            inputs,
            outputs,
        });
    }

    nodes.sort_by(|a, b| a.outputs.cmp(&b.outputs));

    BuildGraphDump { nodes }
}

/// Create a filename-based sorting key cache for stable graph traversal.
///
/// The key prioritizes filename over full path to provide deterministic
/// ordering for dry-run output. This handles test sandbox path variations
/// while maintaining stable output across different environments.
///
/// Note: This is specifically for stable dry-run output in tests and CI.
/// Absolute stability across all possible edge cases is not a goal.
fn create_file_sorting_cache(graph: &Graph) -> HashMap<FileId, (String, usize)> {
    let mut key_cache = HashMap::with_capacity(graph.files.all_ids().size_hint().0);
    for id in graph.files.all_ids() {
        let name = &graph.file(id).name;
        let normalized = name.replace('\\', "/");
        let last_slash = normalized.rfind('/').map_or(0, |i| i + 1);
        key_cache.insert(id, (normalized, last_slash));
    }
    key_cache
}

/// Perform an iteration over the build graph to get the total list of build
/// commands that corresponds to the given inputs.
///
/// This function provides stable output order based on file names and
/// the build graph structure, independent of graph insertion order.
fn stable_toposort_graph(graph: &Graph, inputs: &[FileId]) -> Vec<BuildId> {
    let key_cache = create_file_sorting_cache(graph);
    let by_file_name = |k: &FileId| {
        let (name, last_slash) = &key_cache[k];
        (&name[*last_slash..], name)
    };

    // Sort input files by filename for deterministic order
    let mut input_order = Vec::new();
    input_order.extend_from_slice(inputs);
    input_order.sort_unstable_by_key(by_file_name);

    // DFS stack: (file_id, is_pop)
    let mut stack = Vec::<(FileId, bool)>::new();
    stack.extend(input_order.into_iter().map(|x| (x, false)));
    // Result
    let mut res = vec![];
    // Visited builds set
    let mut vis = HashSet::new();
    // Scratch vec for sorting input. Leave empty when unused.
    let mut sort_in_scratch = vec![];

    while let Some((fid, pop)) = stack.pop() {
        let file = graph.file(fid);
        if let Some(bid) = file.input {
            if !pop {
                if vis.insert(bid) {
                    let build = &graph.builds[bid];
                    stack.push((fid, true));

                    // Sort input files for stable traversal order
                    debug_assert!(sort_in_scratch.is_empty());
                    sort_in_scratch.extend_from_slice(build.explicit_ins());
                    sort_in_scratch.sort_unstable_by_key(by_file_name);
                    stack.extend(sort_in_scratch.iter().copied().map(|x| (x, false)));
                    sort_in_scratch.clear();
                }
            } else {
                res.push(bid);
            }
        }
    }

    res
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::*;

    #[test]
    fn normalizes_shell_command_without_quoting_control_operator() {
        let dir = tempfile::tempdir().expect("test temp dir should be created");
        let source_dir = dir.path().join("project");
        let target_dir = dir.path().join("project-target");
        fs::create_dir_all(&source_dir).expect("source dir should be created");
        fs::create_dir_all(&target_dir).expect("target dir should be created");

        let source_dir = dunce::canonicalize(source_dir).expect("source dir should canonicalize");
        let target_dir = dunce::canonicalize(target_dir).expect("target dir should canonicalize");
        let source_bin = source_dir.join("bin/cc");
        let target_exe = target_dir.join("main");
        let command = format!(
            "{} -o {} && dsymutil {}",
            source_bin.display(),
            target_exe.display(),
            target_exe.display()
        );
        let replacer = PathNormalizer::new_with_target_dir(&source_dir, &target_dir);

        assert_eq!(
            normalize_shell_command(&replacer, &command),
            "./bin/cc -o '$MOON_TARGET_DIR/main' && dsymutil '$MOON_TARGET_DIR/main'"
        );
    }
}
