// moon: The build system and package manager for MoonBit.
// Copyright (C) 2024 International Digital Economy Academy
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
// For inquiries, you can contact us via e-mail at jichuruanjian@idea.edu.cn.

use std::{
    io::Write,
    path::{Path, PathBuf},
    sync::LazyLock,
};

pub use moonutil::dry_run::PathNormalizer;

// Historical test hook name. The payload is now produced from typed dry-run
// command records, not by reparsing an n2 graph.
const ENV_VAR: &str = "MOON_TEST_DUMP_BUILD_GRAPH";
static DRY_RUN_TEST_OUTPUT: LazyLock<Option<String>> =
    LazyLock::new(|| std::env::var(ENV_VAR).ok());

pub struct DryRunCommand<'a> {
    pub command: Option<&'a str>,
    pub command_kind: DryRunCommandKind,
    pub inputs: &'a [PathBuf],
    pub outputs: &'a [PathBuf],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DryRunCommandKind {
    /// Command produced from an argv vector and rendered for the executor.
    Argv,
    /// Command intentionally composed with shell syntax from trusted argv fragments.
    Shell,
}

impl<'a> DryRunCommand<'a> {
    pub fn normalized_command(&self, replacer: &PathNormalizer) -> Option<String> {
        self.command.map(|command| match self.command_kind {
            DryRunCommandKind::Argv => replacer.normalize_command(command),
            DryRunCommandKind::Shell => normalize_shell_command(replacer, command),
        })
    }
}

// This is for shell commandlines generated by lowering from trusted argv
// fragments, not a general-purpose shell rewriter.
fn normalize_shell_command(replacer: &PathNormalizer, command: &str) -> String {
    moonutil::shlex::split_unix(command)
        .into_iter()
        .map(|arg| {
            if is_shell_control_operator(&arg) {
                arg
            } else {
                let normalized = replacer.normalize_command_arg(&arg);
                moonutil::shlex::join_unix(std::iter::once(normalized.as_str()))
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn is_shell_control_operator(s: &str) -> bool {
    matches!(
        s,
        "&&" | "||" | "|" | ";" | "<" | ">" | ">>" | "2>" | "2>&1"
    )
}

pub fn try_debug_dump_commands_to_file<'a>(
    commands: impl IntoIterator<Item = DryRunCommand<'a>>,
    source_dir: &Path,
    target_dir: &Path,
) {
    let Some(out_file) = DRY_RUN_TEST_OUTPUT.as_deref() else {
        return;
    };

    let replacer = PathNormalizer::new_with_target_dir(source_dir, target_dir);
    let mut nodes = commands
        .into_iter()
        .map(|command| {
            let mut inputs = command
                .inputs
                .iter()
                .map(|path| replacer.normalize_path(&path.to_string_lossy()))
                .collect::<Vec<_>>();
            inputs.sort();
            let outputs = command
                .outputs
                .iter()
                .map(|path| replacer.normalize_path(&path.to_string_lossy()))
                .collect::<Vec<_>>();
            DryRunNode {
                command: command.normalized_command(&replacer),
                inputs,
                outputs,
            }
        })
        .collect::<Vec<_>>();

    nodes.sort_by(|a, b| a.outputs.cmp(&b.outputs));
    let file = std::fs::File::create(out_file).expect("Failed to create dry-run dump target");
    let mut writer = std::io::BufWriter::new(file);
    for node in &nodes {
        serde_json::to_writer(&mut writer, node).expect("Failed to dump to target output");
        writeln!(&mut writer).expect("Failed to dump to target output");
    }
}

#[derive(Debug, serde::Serialize)]
struct DryRunNode {
    command: Option<String>,
    inputs: Vec<String>,
    outputs: Vec<String>,
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::*;

    #[test]
    fn normalizes_shell_command_without_quoting_control_operator() {
        let dir = tempfile::tempdir().expect("test temp dir should be created");
        let source_dir = dir.path().join("project");
        let target_dir = dir.path().join("project-target");
        fs::create_dir_all(&source_dir).expect("source dir should be created");
        fs::create_dir_all(&target_dir).expect("target dir should be created");

        let source_dir = dunce::canonicalize(source_dir).expect("source dir should canonicalize");
        let target_dir = dunce::canonicalize(target_dir).expect("target dir should canonicalize");
        let source_bin = source_dir.join("bin/cc");
        let target_exe = target_dir.join("main");
        let command = format!(
            "{} -o {} && dsymutil {}",
            source_bin.display(),
            target_exe.display(),
            target_exe.display()
        );
        let replacer = PathNormalizer::new_with_target_dir(&source_dir, &target_dir);

        assert_eq!(
            normalize_shell_command(&replacer, &command),
            "./bin/cc -o '$MOON_TARGET_DIR/main' && dsymutil '$MOON_TARGET_DIR/main'"
        );
    }
}
